export const propertiesForRent = {
  110079442935: {
    id: 110079442935,
    availableFor: "rent",
    popular: false,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fww1.prweb.com%2Fprfiles%2F2014%2F05%2F31%2F11903401%2FVilla%2520Isla%2520Night.jpg&f=1&nofb=1",
    price: 2200,
    oldPrice: 1495,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Upstairs unit on the preserve, corner unit. Carpet throughout, Tile in bathrooms and kitchen.***Tenants must be approved by HOA with additional application fee***",

    propertyName: "Villa Benhavis, Marbella",
    propertyType: "Apartment",
    bedRooms: 3,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 44,
    viewTypes: "RiverWater",
    country: "DUVAL",
    parcelId: 982520212,
    yearBuilt: 2005,
    area: 124.03,
    architectureStyle: "Other",
    floors: 2,
    provider: "A1 Realty Services LLC",
    subDivision: "MONTREUX",
    familyType: "Single Family - NAPLES, FL",
    address: "8550 TOUCHTON RD, JACKSONVILLE, FL 32216",
    Neighbourhoods: "056-YUKON/WESCONNETT/OAK HILL",
    location: "New York, USA",

    interiorFeatures: {
      pool: true,
    },
  },
  110079442981: {
    id: 110079442981,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn.wheretostay.com%2Fprop_photos%2F0%2F311%2FRoyal-Villa-1-Barbados-12_1200.jpg&f=1&nofb=1",
    price: 2207,
    oldPrice: 15000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "AVAILABLE SEPTEMBER THRU DECEMBER 2022 AT $10k/month & MARCH & APRIL @ $15K/month. RENTED JAN & FEB 2023. Fabulous NEWER home in the gorgeous sought after amenity rich community of Greyhawk! The Pinnacle open floor plan offers just under 2500 square feet with 3 large bedrooms plus a den and a large kitchen island. And most importantly, a SALT-WATER POOL and SPA with an extended lanai to make your next vacation your best ever. This home backs to a lake, just steps from the Clubhouse where you can enjoy the amazing amenities Greyhawk has to offer, a zero gravity pool and lap pool, restaurant and bar, fitness center, tennis and picket ball courts, and golf from May-October. Live the luxury resort-style lifestyle you've always dreamed of! (Social Membership included)",

    propertyName: "The Resort Villa",
    propertyType: "House",
    bedRooms: 3,
    bathRooms: 3,
    carSpaces: 3,
    buildingUnitCount: 1,
    viewTypes: "Lake, Water",
    country: "Collier",
    parcelId: 47780003089,
    yearBuilt: 2020,
    area: 232.26,
    architectureStyle: "Other",
    floors: 1,
    provider: "Berkshire Hathaway HomeServices Florida Realty",
    subDivision: "GREYHAWK AT GOLF CLUB OF THE EVERGLADES",
    familyType: "Single Family - NAPLES, FL",
    address: "9120 Snowy Owl WAY, NAPLES, FL 34120",
    location: "Manitoba, Canada",

    interiorFeatures: {
      sprinklerSystem: true,
      wired: true,
      cableReady: true,
      floorCoverings: "Carpet, Tile",
    },
    exteriorFeatures: {
      waterFront: true,
    },
  },
  110079442983: {
    id: 110079442983,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fluxury-houses.net%2Fwp-content%2Fuploads%2F2020%2F11%2FIncredible-Conceptual-Design-of-Modern-Luxury-Villa-Dubai-169-in-UAE-6-1024x575.jpg&f=1&nofb=1",
    price: 8831,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Come to Naples and stay in a charming, modern, updated 2 bed, 2 bath condo that is a mile to the beach and 2 miles to Downtown. The view from this unit is spectacular. You will feel like you are floating high above the golf course as you enjoy stunning sunsets. The community offers High Point Country Club where all tenants enjoy the 9-hole golf course and pro shop, tennis, pickleball, 6 different pools, and organized events. Washer and dryer are in the unit, elevator building, and rentals are 90-day minimum. Available Oct 1 to Nov 30 @ $3,000 a month. Dec, $6,000. Not available Jan 15 to May 31, 2023",

    propertyName: "Castle Luxury",
    propertyType: "Apartment",
    bedRooms: 2,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 40,
    viewTypes: "Golf Course",
    country: "Collier",
    parcelId: 50590800003,
    yearBuilt: 1981,
    area: 112.13,
    architectureStyle: "Other",
    floors: 1,
    provider: "Berkshire Hathaway HomeServices Florida Realty",
    subDivision: "HIGH POINT",
    familyType: "Single Family - NAPLES, FL",
    address: "29 High Point CIR E, NAPLES, FL 34103",
    location: "Indiana, Canada",

    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Carpet, Tile",
    },
    exteriorFeatures: {
      exteriorTypes: true,
    },
  },
  110079442984: {
    id: 110079442984,
    availableFor: "rent",
    popular: false,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.loyalvillasluxury.com%2Fwp-content%2Fuploads%2F2016%2F09%2Fmain_villa_nikki.jpg&f=1&nofb=1",
    price: 8831,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Huge, 1,325 square feet, one bedroom, one-and-a-half bath condo with fabulous water view. Relax on the spacious lanai and conveniently cook in the Lovely upgraded kitchen. Or go downstairs to dine at one of the four restaurants in this mixed-use community of Bayfront. Enjoy the onsite amenities which include two pools, two spas, two tennis courts, a fitness room, a community room with a kitchen, and gas barbecue grills. Located in Downtown Naples and close to the beach, the excitement of 5th Avenue is just a short stroll away.",

    propertyName: "Justina Villa",
    propertyType: "Apartment",
    bedRooms: 1,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 44,
    viewTypes: "RiverWater",
    country: "Collier",
    parcelId: 2591002366,
    yearBuilt: 2000,
    area: 123.1,
    architectureStyle: "Other",
    floors: 1,
    provider: "Berkshire Hathaway HomeServices Florida Realty",
    subDivision: "BAYFRONT",
    familyType: "Single Family - NAPLES, FL",
    address: "451 BAYFRONT PL, NAPLES, FL 34102-6470",
    location: "Indiana, USA",

    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Tile",
    },
    exteriorFeatures: {
      waterFront: true,
      patio: true,
    },
  },
  110079442957: {
    id: 110079442957,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fthegreekvillas.com%2Fwp-content%2Fuploads%2F2020%2F05%2Fcorfu-luxury-villa-aurora-the-greek-villas-01.jpg&f=1&nofb=1",
    price: 8500,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Immaculate and desirable 2BR/2BA condo with loft! High ceiling. Features elegant designs including gourmet kitchen, fully upgraded with the extra cabinets, stainless steel appliances, custom wood cabinetry, marble tile floor in kitchen, Granite Countertop with hands free Faucet. Great room w/fireplace, dining room, spacious master suite with walk in closet, laundry room with full-size washer and dryer, accent paints, surround sound, crown molding, computer bay. Enjoy a gated community with 16-acre lake, clubhouse, 2 pools, gym, sauna, movie theater, tennis, sand volleyball, indoor basketball & car wash. Walk to dining & shops. Premium laminate flooring throughout. Recently upgraded master bathroom. Nest Thermostat, with the smart lock system. Cordless Graber Blinds.",

    propertyName: "Oceanside Three-Bedroom Villa",
    propertyType: "Apartment",
    bedRooms: 1,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 44,
    viewTypes: "RiverWater",
    country: "DUVAL",
    parcelId: 1541665848,
    yearBuilt: 2005,
    area: 135.92,
    architectureStyle: "Other",
    floors: 3,
    provider: "Florida Homes Realty and Mortgage",
    subDivision: "MONTREUX",
    familyType: "Single Family - NAPLES, FL",
    address: "8550 TOUCHTON RD, JACKSONVILLE, FL 32216",
    Neighbourhoods: "022-GROVE PARK/SANS SOUCI",
    location: "Florida, USA",

    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Tile",
    },
    exteriorFeatures: {
      waterFront: true,
      patio: true,
    },
  },
  210079442935: {
    id: 210079442935,
    availableFor: "rent",
    popular: false,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fi.ytimg.com%2Fvi%2FavkRKeBPq24%2Fmaxresdefault.jpg&f=1&nofb=1",
    price: 5151,
    oldPrice: 3500,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "REMARKABLE DUPLEX UNIT-NOTHING ELSE LIKE IT! FABULOUS 1 BR 1.5 BA HOME W/DEN/GUEST, OFC & MBR SUITE ON LL. BEAUTIFUL FLOW FROM LR TO DR TO EXCEPTIONAL GOURMET KITCHEN-SUBZERO, BOSCH, VIKING-OPEN TO FAMILY ROOM THAT LEADS TO SUPERB PRIVATE LANDSCAPED YARD AND A TWO CAR GARAGE. UTILITIES ARE INCLUDED (HEAT/GAS/ELECTRIC/WATER)!",

    propertyName: "Villa Calipto",
    propertyType: "Townhouse",
    bedRooms: 2,
    bathRooms: 2,
    carSpaces: 0,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "Cook",
    yearBuilt: 1890,
    area: 124.03,
    architectureStyle: "Other",
    floors: 3,
    provider: "Compass Real Estate",
    address: "1221 W BARRY Avenue, Chicago, IL 60657",
    Neighbourhoods: "CHI - Lake View",
    location: "Alabama, USA",

    interiorFeatures: {
      patio: true,
    },
  },
  110079442923: {
    id: 110079442923,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.cabovillas.com%2FProperties%2FVillas%2FVilla_Haydee%2FFULL%2FVilla_Haydee-1.jpg&f=1&nofb=1https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvillapearl-ibiza.com%2Fwp-content%2Fuploads%2F2018%2F08%2FPEARL-04-e1533820519709.jpg&f=1&nofb=1",
    price: 2649,
    oldPrice: 1800,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Newly completed studio Accessory Dwelling unit with parking pad and gated access via alley. Fenced area separate from front house backyard. Great location One large room with own bath, and own laundry hookups.",

    propertyName: "Villa PEARL IBIZA",
    propertyType: "Apartment",
    bedRooms: 1,
    bathRooms: 1,
    carSpaces: 1,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "Los Angeles",
    yearBuilt: 2022,
    area: 37.16,
    subDivision: "Wrigley Area (WR)",
    architectureStyle: "Other",
    floors: 3,
    provider: "Brian P. Thornton, Broker (Thornton Realty)",
    address: "2710 Chestnut Street, Long Beach, CA 90806",
    location: "Florida, USA",
  },
  110079444237: {
    id: 110079444237,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.vacation-key.com%2Fphotos%2F1%2F0%2F106254-5.jpg&f=1&nofb=1",
    price: 3529,
    oldPrice: 2400,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Lovely 3 bedroom 1 bath rental with hardwood floors, gas fireplace beautiful eat in kitchen with granite counters and nice open floor plan, wall unit air conditioner. Sliders out to deck and fenced in back yard, Will be available to show 9/10/22 Call now for an appointment.",

    propertyName: "Villa Aura",
    propertyType: "House",
    bedRooms: 3,
    bathRooms: 1,
    carSpaces: 0,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "OCEAN",
    yearBuilt: 1991,
    area: 89.19,
    subDivision: "Ocean Acres",
    franchise: "RE/MAX International",
    architectureStyle: "Rambler",
    floors: 1,
    provider: "RE/MAX At Barnegat Bay",
    address: "1179 GALLEY AVENUE, MANAHAWKIN, NJ 08050",
    neighbourhoods: "STAFFORD TWP",
    location: "Alabama, USA",

    interiorFeatures: {
      firePlace: true,
      attic: true,
    },
  },
  110079444234: {
    id: 110079444234,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.cyprus-villa-retreats.com%2Fwp-content%2Fuploads%2F2020%2F01%2FMG_5160-1.jpg&f=1&nofb=1",
    price: 4852,
    oldPrice: 3300,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Beautiful 4 level town home in Cowan Crossing. Located just mins from Central Park, shopping, dining, I-95. DC commuter, no worries downtown Fredericksburg train station just mins away. This great home is loaded with upgrades, beautiful wood floors, chefs kitchen w/ double wall ovens, gas cooktop, large island w/ granite counters & ss appliances. Large open floor plan w/ generous room sizes. Lower level rec room & half bath w/ access to rear lower level deck. Bedroom level features primary suite w/ en-suite & large walk in closet. 2 additional bedrooms, well appointed hall bath and stackable washer and dryer round out this level. Up one more level and you reach a 2nd rec room, need a 4th bedroom, no worries, add a wardrobe and you are set. Entertaining is made easy with the large open floor plan, Double level deck and beautiful finishes. Call today and make this your new home.",

    propertyName: "Amazing Modern Luxury Villa on Naithon Beach",
    propertyType: "Townhouse",
    bedRooms: 3,
    bathRooms: 2,
    carSpaces: 2,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "FREDERICKSBURG CITY",
    yearBuilt: 1991,
    area: 202.34,
    subDivision: "Cowan Crossing",
    franchise: "RE/MAX International",
    architectureStyle: "Other",
    floors: 1,
    provider: "Pathfinder Properties LLC",
    address: "1206 RAMBLE DRIVE, FREDERICKSBURG, VA 22401",
    neighbourhoods: "STAFFORD TWP",
    location: "New York, USA",

    interiorFeatures: {
      firePlace: true,
      attic: true,
      cellinFan: true,
    },
    exteriorFeatures: {
      basement: true,
    },
  },
  110079444227: {
    id: 110079444227,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fbugbye.net%2Fwp-content%2Fuploads%2F2014%2F09%2FLuxury-Villa-house-4.jpg&f=1&nofb=1",
    price: 3088,
    oldPrice: 2100,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Are you looking for a great home close to PAX? Welcome home to this gorgeous 4 bed/ 3.5 bath townhome. Located within 200 yards of the majestic Chesapeake Bay and less than 5 minutes from PAX River Naval Air Station. This pristine home has been freshly painted, has new hardwood floors, and a brand new high efficiency HVAC! Enjoy your evenings relaxing on the brand new deck overlooking the woods and yard. New stainless steel kitchen appliances, tankless gas water heater, and many more upgrades throughout. Located on a corner lot and close to the neighborhood beach access and walking/biking trails. Set up like a beach house, the main level has a garage, laundry/mudroom, bath, and flex room that may be used as a 4th possible bedroom. On the 2nd level you will find a spacious kitchen, dining room, living room, and 1/2 bath. The top floor features a master suite with en suite bath, recently update hall bath, and two additional bedrooms. Well cared for and move-in ready! Don't miss your chance to live in this great home!",

    propertyName: "Small villa Casetta",
    propertyType: "Townhouse",
    bedRooms: 3,
    bathRooms: 4,
    carSpaces: 0,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "SAINT MARYS",
    yearBuilt: 2002,
    area: 190.45,
    subDivision: "Villas On Waters Edge",
    franchise: "RE/MAX International",
    architectureStyle: "Other",
    floors: 1,
    provider: "RE/MAX One",
    address: "48383 SUNBURST DRIVE, LEXINGTON PARK, MD 20653",
    neighbourhoods: "STAFFORD TWP",
    location: "New York, USA",

    interiorFeatures: {
      firePlace: true,
      attic: true,
      cellinFan: true,
    },
    exteriorFeatures: {
      basement: true,
      exteriorTypes: "Vinyl Siding",
    },
  },
  111179442935: {
    id: 111179442935,
    availableFor: "rent",
    popular: false,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.john-taylor.com%2Fsale-villa-palm-jumeirah-ori100-V0341DU-61109170.jpg&f=1&nofb=1",
    price: 1200,
    oldPrice: 1795,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Upstairs unit on the preserve, corner unit. Carpet throughout, Tile in bathrooms and kitchen.***Tenants must be approved by HOA with additional application fee***",

    propertyName: "Nerea - villa Nerea Amalfi Coast",
    propertyType: "Apartment",
    bedRooms: 2,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 8,
    viewTypes: "RiverWater",
    country: "DUVAL",
    parcelId: 982520212,
    yearBuilt: 2005,
    area: 124.03,
    architectureStyle: "Other",
    floors: 2,
    provider: "A1 Realty Services LLC",
    subDivision: "MONTREUX",
    familyType: "Single Family - NAPLES, FL",
    address: "8550 TOUCHTON RD, JACKSONVILLE, FL 32216",
    Neighbourhoods: "056-YUKON/WESCONNETT/OAK HILL",
    location: "New York, USA",

    interiorFeatures: {
      pool: true,
    },
  },
  112279442981: {
    id: 112279442981,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.zekkeicollection.com%2Fwp-content%2Fuploads%2FVilla-Canggu-2.jpg&f=1&nofb=1",
    price: 3407,
    oldPrice: 15000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "AVAILABLE SEPTEMBER THRU DECEMBER 2022 AT $10k/month & MARCH & APRIL @ $15K/month. RENTED JAN & FEB 2023. Fabulous NEWER home in the gorgeous sought after amenity rich community of Greyhawk! The Pinnacle open floor plan offers just under 2500 square feet with 3 large bedrooms plus a den and a large kitchen island. And most importantly, a SALT-WATER POOL and SPA with an extended lanai to make your next vacation your best ever. This home backs to a lake, just steps from the Clubhouse where you can enjoy the amazing amenities Greyhawk has to offer, a zero gravity pool and lap pool, restaurant and bar, fitness center, tennis and picket ball courts, and golf from May-October. Live the luxury resort-style lifestyle you've always dreamed of! (Social Membership included)",

    propertyName: "The Resort Villa",
    propertyType: "House",
    bedRooms: 1,
    bathRooms: 1,
    carSpaces: 0,
    buildingUnitCount: 1,
    viewTypes: "Lake, Water",
    country: "Collier",
    parcelId: 47780003089,
    yearBuilt: 2022,
    area: 212.26,
    architectureStyle: "Other",
    floors: 1,
    provider: "Berkshire Hathaway HomeServices Florida Realty",
    subDivision: "GREYHAWK AT GOLF CLUB OF THE EVERGLADES",
    familyType: "Single Family - NAPLES, FL",
    address: "9120 Snowy Owl WAY, NAPLES, FL 34120",
    location: "Manitoba, Canada",

    interiorFeatures: {
      sprinklerSystem: true,
      wired: true,
      cableReady: true,
      floorCoverings: "Carpet, Tile",
    },
    exteriorFeatures: {
      waterFront: true,
    },
  },
  110072222983: {
    id: 110072222983,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fthegreekvillas.com%2Fwp-content%2Fuploads%2F2019%2F10%2Fparos-villa-graff-the-greek-villas-60.JPG.d72.jpg&f=1&nofb=1",
    price: 7831,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Come to Naples and stay in a charming, modern, updated 2 bed, 2 bath condo that is a mile to the beach and 2 miles to Downtown. The view from this unit is spectacular. You will feel like you are floating high above the golf course as you enjoy stunning sunsets. The community offers High Point Country Club where all tenants enjoy the 9-hole golf course and pro shop, tennis, pickleball, 6 different pools, and organized events. Washer and dryer are in the unit, elevator building, and rentals are 90-day minimum. Available Oct 1 to Nov 30 @ $3,000 a month. Dec, $6,000. Not available Jan 15 to May 31, 2023",

    propertyName: "Luxury villa Raffaella",
    propertyType: "Apartment",
    bedRooms: 2,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 40,
    viewTypes: "Golf Course",
    country: "Collier",
    parcelId: 50590800003,
    yearBuilt: 1981,
    area: 712.13,
    architectureStyle: "Other",
    floors: 1,
    provider: "Berkshire Hathaway HomeServices Florida Realty",
    subDivision: "HIGH POINT",
    familyType: "Single Family - NAPLES, FL",
    address: "29 High Point CIR E, NAPLES, FL 34103",
    location: "Indiana, Canada",

    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Carpet, Tile",
    },
    exteriorFeatures: {
      exteriorTypes: true,
    },
  },
  110079466684: {
    id: 110079466684,
    availableFor: "rent",
    popular: false,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftheluxuryvillacollection.com%2Fwp-content%2Fuploads%2F2019%2F06%2FVilla-Maran-luxury-villa-ultra-modern-rental.jpg&f=1&nofb=1",
    price: 7831,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Huge, 1,325 square feet, one bedroom, one-and-a-half bath condo with fabulous water view. Relax on the spacious lanai and conveniently cook in the Lovely upgraded kitchen. Or go downstairs to dine at one of the four restaurants in this mixed-use community of Bayfront. Enjoy the onsite amenities which include two pools, two spas, two tennis courts, a fitness room, a community room with a kitchen, and gas barbecue grills. Located in Downtown Naples and close to the beach, the excitement of 5th Avenue is just a short stroll away.",

    propertyName: "Versace villa ",
    propertyType: "Apartment",
    bedRooms: 1,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 44,
    viewTypes: "RiverWater",
    country: "Collier",
    parcelId: 2591002366,
    yearBuilt: 2000,
    area: 613.1,
    architectureStyle: "Other",
    floors: 1,
    provider: "Berkshire Hathaway HomeServices Florida Realty",
    subDivision: "BAYFRONT",
    familyType: "Single Family - NAPLES, FL",
    address: "451 BAYFRONT PL, NAPLES, FL 34102-6470",
    location: "Indiana, USA",

    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Tile",
    },
    exteriorFeatures: {
      waterFront: true,
      patio: true,
    },
  },
  110079411111: {
    id: 110079411111,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.retalkmena.com%2Fsites%2Fdefault%2Ffiles%2Fstyles%2Farticle-full%2Fpublic%2F7905232625ceff3b16c2184.97859861_03dc5ad77e_1920.jpg&f=1&nofb=1",
    price: 8831,
    oldPrice: 3000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Immaculate and desirable 2BR/2BA condo with loft! High ceiling. Features elegant designs including gourmet kitchen, fully upgraded with the extra cabinets, stainless steel appliances, custom wood cabinetry, marble tile floor in kitchen, Granite Countertop with hands free Faucet. Great room w/fireplace, dining room, spacious master suite with walk in closet, laundry room with full-size washer and dryer, accent paints, surround sound, crown molding, computer bay. Enjoy a gated community with 16-acre lake, clubhouse, 2 pools, gym, sauna, movie theater, tennis, sand volleyball, indoor basketball & car wash. Walk to dining & shops. Premium laminate flooring throughout. Recently upgraded master bathroom. Nest Thermostat, with the smart lock system. Cordless Graber Blinds.",

    propertyName: "Villa Medici",
    propertyType: "Apartment",
    bedRooms: 3,
    bathRooms: 2,
    carSpaces: 1,
    buildingUnitCount: 0,
    viewTypes: "RiverWater",
    country: "DUVAL",
    parcelId: 1541665848,
    yearBuilt: 2005,
    area: 334.92,
    architectureStyle: "Other",
    floors: 3,
    provider: "Florida Homes Realty and Mortgage",
    subDivision: "MONTREUX",
    familyType: "Single Family - NAPLES, FL",
    address: "8550 TOUCHTON RD, JACKSONVILLE, FL 32216",
    Neighbourhoods: "022-GROVE PARK/SANS SOUCI",
    location: "Florida, USA",

    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Tile",
    },
    exteriorFeatures: {
      waterFront: true,
      patio: true,
    },
  },
  210073333935: {
    id: 210073333935,
    availableFor: "rent",
    popular: false,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.nelsontasman.nz%2Fassets%2FProductImages%2F3.Villa-firepit.jpg&f=1&nofb=1",
    price: 5351,
    oldPrice: 4500,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "REMARKABLE DUPLEX UNIT-NOTHING ELSE LIKE IT! FABULOUS 1 BR 1.5 BA HOME W/DEN/GUEST, OFC & MBR SUITE ON LL. BEAUTIFUL FLOW FROM LR TO DR TO EXCEPTIONAL GOURMET KITCHEN-SUBZERO, BOSCH, VIKING-OPEN TO FAMILY ROOM THAT LEADS TO SUPERB PRIVATE LANDSCAPED YARD AND A TWO CAR GARAGE. UTILITIES ARE INCLUDED (HEAT/GAS/ELECTRIC/WATER)!",

    propertyName: "Villa Calipto",
    propertyType: "Townhouse",
    bedRooms: 2,
    bathRooms: 2,
    carSpaces: 0,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "Cook",
    yearBuilt: 1890,
    area: 224.03,
    architectureStyle: "Other",
    floors: 3,
    provider: "Compass Real Estate",
    address: "1221 W BARRY Avenue, Chicago, IL 60657",
    Neighbourhoods: "CHI - Lake View",
    location: "Alabama, USA",

    interiorFeatures: {
      patio: true,
    },
  },
  110071212923: {
    id: 110071212923,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.panchshil.com%2Fyoovillas%2Fassets%2Fimages%2Fbanners%2FJWqyrL0jS8bAGwdQh4mYjpg.jpg&f=1&nofb=1",
    price: 2649,
    oldPrice: 1800,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Newly completed studio Accessory Dwelling unit with parking pad and gated access via alley. Fenced area separate from front house backyard. Great location One large room with own bath, and own laundry hookups.",

    propertyName: "Villa PEARL IBIZA",
    propertyType: "Apartment",
    bedRooms: 1,
    bathRooms: 1,
    carSpaces: 1,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "Los Angeles",
    yearBuilt: 2015,
    area: 357.16,
    subDivision: "Wrigley Area (WR)",
    architectureStyle: "Other",
    floors: 3,
    provider: "Brian P. Thornton, Broker (Thornton Realty)",
    address: "2710 Chestnut Street, Long Beach, CA 90806",
    location: "Florida, USA",
  },
  110079994237: {
    id: 110079994237,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimg1.goodfon.com%2Fwallpaper%2Fbig%2F2%2F76%2Fhome-villa-pool-dom-villa.jpg&f=1&nofb=1",
    price: 9929,
    oldPrice: 10000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Lovely 3 bedroom 1 bath rental with hardwood floors, gas fireplace beautiful eat in kitchen with granite counters and nice open floor plan, wall unit air conditioner. Sliders out to deck and fenced in back yard, Will be available to show 9/10/22 Call now for an appointment.",

    propertyName: "Ranch/Rambler",
    propertyType: "House",
    bedRooms: 3,
    bathRooms: 1,
    carSpaces: 0,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "OCEAN",
    yearBuilt: 1991,
    area: 89.19,
    subDivision: "Ocean Acres",
    franchise: "RE/MAX International",
    architectureStyle: "Rambler",
    floors: 1,
    provider: "RE/MAX At Barnegat Bay",
    address: "1179 GALLEY AVENUE, MANAHAWKIN, NJ 08050",
    neighbourhoods: "STAFFORD TWP",
    location: "Alabama, USA",

    interiorFeatures: {
      firePlace: true,
      attic: true,
    },
  },
  110079554234: {
    id: 110079554234,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.lemenara.com%2Fimages%2F2bedroom-pool_villa-beachfront-02room.jpg&f=1&nofb=1",
    price: 2252,
    oldPrice: 3300,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Beautiful 4 level town home in Cowan Crossing. Located just mins from Central Park, shopping, dining, I-95. DC commuter, no worries downtown Fredericksburg train station just mins away. This great home is loaded with upgrades, beautiful wood floors, chefs kitchen w/ double wall ovens, gas cooktop, large island w/ granite counters & ss appliances. Large open floor plan w/ generous room sizes. Lower level rec room & half bath w/ access to rear lower level deck. Bedroom level features primary suite w/ en-suite & large walk in closet. 2 additional bedrooms, well appointed hall bath and stackable washer and dryer round out this level. Up one more level and you reach a 2nd rec room, need a 4th bedroom, no worries, add a wardrobe and you are set. Entertaining is made easy with the large open floor plan, Double level deck and beautiful finishes. Call today and make this your new home.",

    propertyName: "Interior Row/Townhouse",
    propertyType: "Townhouse",
    bedRooms: 1,
    bathRooms: 2,
    carSpaces: 2,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "FREDERICKSBURG CITY",
    yearBuilt: 1991,
    area: 202.34,
    subDivision: "Cowan Crossing",
    franchise: "RE/MAX International",
    architectureStyle: "Other",
    floors: 1,
    provider: "Pathfinder Properties LLC",
    address: "1206 RAMBLE DRIVE, FREDERICKSBURG, VA 22401",
    neighbourhoods: "STAFFORD TWP",
    location: "New York, USA",

    interiorFeatures: {
      firePlace: true,
      attic: true,
      cellinFan: true,
    },
    exteriorFeatures: {
      basement: true,
    },
  },
  110034345121: {
    id: 110034345121,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmanage.isleblue.co%2Fuploads%2Fvillas%2Fimages%2F4978%2Famalfi-coast-villa-nirvana-2019-header_large.jpg&f=1&nofb=1",
    price: 6088,
    oldPrice: 9100,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Are you looking for a great home close to PAX? Welcome home to this gorgeous 4 bed/ 3.5 bath townhome. Located within 200 yards of the majestic Chesapeake Bay and less than 5 minutes from PAX River Naval Air Station. This pristine home has been freshly painted, has new hardwood floors, and a brand new high efficiency HVAC! Enjoy your evenings relaxing on the brand new deck overlooking the woods and yard. New stainless steel kitchen appliances, tankless gas water heater, and many more upgrades throughout. Located on a corner lot and close to the neighborhood beach access and walking/biking trails. Set up like a beach house, the main level has a garage, laundry/mudroom, bath, and flex room that may be used as a 4th possible bedroom. On the 2nd level you will find a spacious kitchen, dining room, living room, and 1/2 bath. The top floor features a master suite with en suite bath, recently update hall bath, and two additional bedrooms. Well cared for and move-in ready! Don't miss your chance to live in this great home!",

    propertyName: "End Of Row/Townhouse, Side-by-Side",
    propertyType: "Townhouse",
    bedRooms: 3,
    bathRooms: 2,
    carSpaces: 4,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "SAINT MARYS",
    yearBuilt: 2002,
    area: 193.45,
    subDivision: "Villas On Waters Edge",
    franchise: "RE/MAX International",
    architectureStyle: "Other",
    floors: 1,
    provider: "RE/MAX One",
    address: "48383 SUNBURST DRIVE, LEXINGTON PARK, MD 20653",
    neighbourhoods: "STAFFORD TWP",
    location: "New York, USA",

    interiorFeatures: {
      firePlace: true,
      attic: true,
      cellinFan: true,
    },
    exteriorFeatures: {
      basement: true,
      exteriorTypes: "Vinyl Siding",
    },
  },
  190034345227: {
    id: 190034345227,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftrueluxuryvillas.com%2Fmedia%2Fdefault%2F0001%2F02%2F73566ac8b795a9d79a2b3db20d9bb40f5340e75c.jpeg&f=1&nofb=1",
    price: 5088,
    oldPrice: 6100,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Are you looking for a great home close to PAX? Welcome home to this gorgeous 4 bed/ 3.5 bath townhome. Located within 200 yards of the majestic Chesapeake Bay and less than 5 minutes from PAX River Naval Air Station. This pristine home has been freshly painted, has new hardwood floors, and a brand new high efficiency HVAC! Enjoy your evenings relaxing on the brand new deck overlooking the woods and yard. New stainless steel kitchen appliances, tankless gas water heater, and many more upgrades throughout. Located on a corner lot and close to the neighborhood beach access and walking/biking trails. Set up like a beach house, the main level has a garage, laundry/mudroom, bath, and flex room that may be used as a 4th possible bedroom. On the 2nd level you will find a spacious kitchen, dining room, living room, and 1/2 bath. The top floor features a master suite with en suite bath, recently update hall bath, and two additional bedrooms. Well cared for and move-in ready! Don't miss your chance to live in this great home!",

    propertyName: "Start Of Bow",
    propertyType: "Townhouse",
    bedRooms: 4,
    bathRooms: 2,
    carSpaces: 1,
    condoFloorNum: 2,
    viewTypes: "RiverWater",
    country: "SAINT MARYS",
    yearBuilt: 2002,
    area: 993.45,
    subDivision: "Villas On Waters Edge",
    franchise: "RE/MAX International",
    architectureStyle: "Other",
    floors: 1,
    provider: "RE/MAX One",
    address: "48383 SUNBURST DRIVE, LEXINGTON PARK, MD 20653",
    neighbourhoods: "STAFFORD TWP",
    location: "New York, USA",

    interiorFeatures: {
      firePlace: true,
      attic: true,
      cellinFan: true,
    },
    exteriorFeatures: {
      basement: true,
      exteriorTypes: "Vinyl Siding",
    },
  },
  199034345227: {
    id: 199034345227,
    availableFor: "rent",
    popular: true,
    imageUrl:
      "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.romeanditaly.com%2Fwp-content%2Fuploads%2F2019%2F11%2FVilla-D%25E2%2580%2599Este-%25E2%2580%2593-Tivoli-03-min-1280x789.jpg&f=1&nofb=1",
    price: 6288,
    oldPrice: 7100,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Are you looking for a great home close to PAX? Welcome home to this gorgeous 4 bed/ 3.5 bath townhome. Located within 200 yards of the majestic Chesapeake Bay and less than 5 minutes from PAX River Naval Air Station. This pristine home has been freshly painted, has new hardwood floors, and a brand new high efficiency HVAC! Enjoy your evenings relaxing on the brand new deck overlooking the woods and yard. New stainless steel kitchen appliances, tankless gas water heater, and many more upgrades throughout. Located on a corner lot and close to the neighborhood beach access and walking/biking trails. Set up like a beach house, the main level has a garage, laundry/mudroom, bath, and flex room that may be used as a 4th possible bedroom. On the 2nd level you will find a spacious kitchen, dining room, living room, and 1/2 bath. The top floor features a master suite with en suite bath, recently update hall bath, and two additional bedrooms. Well cared for and move-in ready! Don't miss your chance to live in this great home!",

    propertyName: "Townhouse, Side-by-Side",
    propertyType: "Townhouse",
    bedRooms: 1,
    bathRooms: 1,
    carSpaces: 1,
    condoFloorNum: 1,
    viewTypes: "RiverWater",
    country: "SAINT MARYS",
    yearBuilt: 2002,
    area: 593.45,
    subDivision: "Villas On Waters Edge",
    franchise: "RE/MAX International",
    architectureStyle: "Other",
    floors: 1,
    provider: "RE/MAX One",
    address: "48383 SUNBURST DRIVE, LEXINGTON PARK, MD 20653",
    neighbourhoods: "STAFFORD TWP",
    location: "Manitoba, Canada",

    interiorFeatures: {
      firePlace: true,
      attic: true,
      cellinFan: true,
    },
    exteriorFeatures: {
      basement: true,
      exteriorTypes: "Vinyl Siding",
    },
  },
};
