export const estatesPropertiesForRent = {
  110079442981: {
    id: 110079442981,
    imageUrl:
      "https://s1.rea.global/img/130x98-resize/listhub/us/582f6b0fa12ca10649ee0d40271df3c3.jpg",
    currentPrice: 22077,
    oldPrice: 15000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "AVAILABLE SEPTEMBER THRU DECEMBER 2022 AT $10k/month & MARCH & APRIL @ $15K/month. RENTED JAN & FEB 2023. Fabulous NEWER home in the gorgeous sought after amenity rich community of Greyhawk! The Pinnacle open floor plan offers just under 2500 square feet with 3 large bedrooms plus a den and a large kitchen island. And most importantly, a SALT-WATER POOL and SPA with an extended lanai to make your next vacation your best ever. This home backs to a lake, just steps from the Clubhouse where you can enjoy the amazing amenities Greyhawk has to offer, a zero gravity pool and lap pool, restaurant and bar, fitness center, tennis and picket ball courts, and golf from May-October. Live the luxury resort-style lifestyle you've always dreamed of! (Social Membership included)",
    basicInfo: {
      propertyType: "House",
      bedRooms: 3,
      bathRooms: 3,
      carSpaces: 3,
      buildingUnitCount: 1,
      viewTypes: "Lake, Water",
      country: "Collier",
      parcelId: 47780003089,
      yearBuilt: 2020,
      houseSize: 232.26,
      architectureStyle: "Other",
      floors: 1,
      provider: "Berkshire Hathaway HomeServices Florida Realty",
      subDivision: "GREYHAWK AT GOLF CLUB OF THE EVERGLADES",
      familyType: "Single Family - NAPLES, FL",
      address: "9120 Snowy Owl WAY, NAPLES, FL 34120",
    },
    interiorFeatures: {
      sprinklerSystem: true,
      wired: true,
      cableReady: true,
      floorCoverings: "Carpet, Tile",
    },
    exteriorFeatures: {
      waterFront: true,
    },
  },
  110079442983: {
    id: 110079442983,
    imageUrl:
      "https://s1.rea.global/img/668x501-resize/listhub/us/aafdd5831e9712b3e67dcecf172e7c0f.jpg",
    currentPrice: 8831,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Come to Naples and stay in a charming, modern, updated 2 bed, 2 bath condo that is a mile to the beach and 2 miles to Downtown. The view from this unit is spectacular. You will feel like you are floating high above the golf course as you enjoy stunning sunsets. The community offers High Point Country Club where all tenants enjoy the 9-hole golf course and pro shop, tennis, pickleball, 6 different pools, and organized events. Washer and dryer are in the unit, elevator building, and rentals are 90-day minimum. Available Oct 1 to Nov 30 @ $3,000 a month. Dec, $6,000. Not available Jan 15 to May 31, 2023",
    basicInfo: {
      propertyType: "Apartment",
      bedRooms: 2,
      bathRooms: 2,
      carSpaces: 1,
      buildingUnitCount: 40,
      viewTypes: "Golf Course",
      country: "Collier",
      parcelId: 50590800003,
      yearBuilt: 1981,
      houseSize: 112.13,
      architectureStyle: "Other",
      floors: 1,
      provider: "Berkshire Hathaway HomeServices Florida Realty",
      subDivision: "HIGH POINT",
      familyType: "Single Family - NAPLES, FL",
      address: "29 High Point CIR E, NAPLES, FL 34103",
    },
    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Carpet, Tile",
    },
    exteriorFeatures: {
      exteriorTypes: true,
    },
  },
  110079442984: {
    id: 110079442984,
    imageUrl:
      "https://s1.rea.global/img/668x501-resize/listhub/us/ff79b4893657323915f4af468cb3ff29.jpg",
    currentPrice: 8831,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Huge, 1,325 square feet, one bedroom, one-and-a-half bath condo with fabulous water view. Relax on the spacious lanai and conveniently cook in the Lovely upgraded kitchen. Or go downstairs to dine at one of the four restaurants in this mixed-use community of Bayfront. Enjoy the onsite amenities which include two pools, two spas, two tennis courts, a fitness room, a community room with a kitchen, and gas barbecue grills. Located in Downtown Naples and close to the beach, the excitement of 5th Avenue is just a short stroll away.",
    basicInfo: {
      propertyType: "Apartment",
      bedRooms: 1,
      bathRooms: 2,
      carSpaces: 1,
      buildingUnitCount: 44,
      viewTypes: "RiverWater",
      country: "Collier",
      parcelId: 2591002366,
      yearBuilt: 2000,
      houseSize: 123.1,
      architectureStyle: "Other",
      floors: 1,
      provider: "Berkshire Hathaway HomeServices Florida Realty",
      subDivision: "BAYFRONT",
      familyType: "Single Family - NAPLES, FL",
      address: "451 BAYFRONT PL, NAPLES, FL 34102-6470",
    },
    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Tile",
    },
    exteriorFeatures: {
      waterFront: true,
      patio: true,
    },
  },
  110079442957: {
    id: 110079442957,
    imageUrl:
      "https://s1.rea.global/img/668x501-resize/listhub/us/ff79b4893657323915f4af468cb3ff29.jpg",
    currentPrice: 8831,
    oldPrice: 6000,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Immaculate and desirable 2BR/2BA condo with loft! High ceiling. Features elegant designs including gourmet kitchen, fully upgraded with the extra cabinets, stainless steel appliances, custom wood cabinetry, marble tile floor in kitchen, Granite Countertop with hands free Faucet. Great room w/fireplace, dining room, spacious master suite with walk in closet, laundry room with full-size washer and dryer, accent paints, surround sound, crown molding, computer bay. Enjoy a gated community with 16-acre lake, clubhouse, 2 pools, gym, sauna, movie theater, tennis, sand volleyball, indoor basketball & car wash. Walk to dining & shops. Premium laminate flooring throughout. Recently upgraded master bathroom. Nest Thermostat, with the smart lock system. Cordless Graber Blinds.",
    basicInfo: {
      propertyType: "Apartment",
      bedRooms: 1,
      bathRooms: 2,
      carSpaces: 1,
      buildingUnitCount: 44,
      viewTypes: "RiverWater",
      country: "DUVAL",
      parcelId: 1541665848,
      yearBuilt: 2005,
      houseSize: 135.92,
      architectureStyle: "Other",
      floors: 3,
      provider: "Florida Homes Realty and Mortgage",
      subDivision: "MONTREUX",
      familyType: "Single Family - NAPLES, FL",
      address: "8550 TOUCHTON RD, JACKSONVILLE, FL 32216",
      Neighbourhoods: "022-GROVE PARK/SANS SOUCI",
    },
    interiorFeatures: {
      cableReady: true,
      floorCoverings: "Tile",
    },
    exteriorFeatures: {
      waterFront: true,
      patio: true,
    },
  },
  110079442935: {
    id: 110079442935,
    imageUrl:
      "https://s1.rea.global/img/668x501-resize/listhub/us/dadcb4546ef39eb5de748ab44de197dc.jpg",
    currentPrice: 2200,
    oldPrice: 1495,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Upstairs unit on the preserve, corner unit. Carpet throughout, Tile in bathrooms and kitchen.***Tenants must be approved by HOA with additional application fee***",
    basicInfo: {
      propertyType: "Apartment",
      bedRooms: 3,
      bathRooms: 2,
      carSpaces: 1,
      buildingUnitCount: 44,
      viewTypes: "RiverWater",
      country: "DUVAL",
      parcelId: 982520212,
      yearBuilt: 2005,
      houseSize: 124.03,
      architectureStyle: "Other",
      floors: 2,
      provider: "A1 Realty Services LLC",
      subDivision: "MONTREUX",
      familyType: "Single Family - NAPLES, FL",
      address: "8550 TOUCHTON RD, JACKSONVILLE, FL 32216",
      Neighbourhoods: "056-YUKON/WESCONNETT/OAK HILL",
    },
    interiorFeatures: {
      pool: true,
    },
  },
  210079442935: {
    id: 210079442935,
    imageUrl:
      "https://s1.rea.global/img/1620x730-resize,r=0,g=0,b=0/listhub/us/ba8c965ede349cabee1c0b607231853f.jpg",
    currentPrice: 5151,
    oldPrice: 3500,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "REMARKABLE DUPLEX UNIT-NOTHING ELSE LIKE IT! FABULOUS 1 BR 1.5 BA HOME W/DEN/GUEST, OFC & MBR SUITE ON LL. BEAUTIFUL FLOW FROM LR TO DR TO EXCEPTIONAL GOURMET KITCHEN-SUBZERO, BOSCH, VIKING-OPEN TO FAMILY ROOM THAT LEADS TO SUPERB PRIVATE LANDSCAPED YARD AND A TWO CAR GARAGE. UTILITIES ARE INCLUDED (HEAT/GAS/ELECTRIC/WATER)!",
    basicInfo: {
      propertyType: "Townhouse",
      bedRooms: 2,
      bathRooms: 2,
      carSpaces: 0,
      condoFloorNum: 1,
      viewTypes: "RiverWater",
      country: "Cook",
      yearBuilt: 1890,
      houseSize: 124.03,
      architectureStyle: "Other",
      floors: 3,
      provider: "Compass Real Estate",
      address: "1221 W BARRY Avenue, Chicago, IL 60657",
      Neighbourhoods: "CHI - Lake View",
    },
    interiorFeatures: {
      patio: true,
    },
  },
  110079442923: {
    id: 110079442923,
    imageUrl:
      "https://s1.rea.global/img/1620x730-resize,r=0,g=0,b=0/listhub/us/57089376cd39006a191a0223b48f4439.jpg",
    currentPrice: 2649,
    oldPrice: 1800,
    currencyType: "AUD",
    currencyLogo: "$",
    description:
      "Newly completed studio Accessory Dwelling unit with parking pad and gated access via alley. Fenced area separate from front house backyard. Great location One large room with own bath, and own laundry hookups.",
    basicInfo: {
      propertyType: "Apartment",
      bedRooms: 1,
      bathRooms: 1,
      carSpaces: 1,
      condoFloorNum: 1,
      viewTypes: "RiverWater",
      country: "Los Angeles",
      yearBuilt: 2022,
      houseSize: 37.16,
      subDivision: "Wrigley Area (WR)",
      architectureStyle: "Other",
      floors: 3,
      provider: "Brian P. Thornton, Broker (Thornton Realty)",
      address: "2710 Chestnut Street, Long Beach, CA 90806",
    },
  },
};
